spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

oauth:
  github:
    client-id: ${GITHUB_CLIENT_ID:}
    client-secret: ${GITHUB_CLIENT_SECRET:}
    redirect-uri: ${GITHUB_REDIRECT_URI:}

jwt:
  expirationMs: 900000
  refreshExpirationMs: 1209600000

cookie:
  secure:
    false

admin:
  username: ${ADMIN_USERNAME:}
  password: ${ADMIN_PASSWORD:}
  nickname: ${ADMIN_NICKNAME:관리자}