spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  expirationMs: 900000
  refreshExpirationMs: 1209600000

cookie:
  secure:
    false

admin:
  username: ${ADMIN_USERNAME:}
  password: ${ADMIN_PASSWORD:}
  nickname: ${ADMIN_NICKNAME:관리자}

portone:
  api-secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}
  webhook-secret: ${PORTONE_WEBHOOK_SECRET}